# Generated by Django 2.1.2 on 2018-10-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
