# Generated by Django 2.1.2 on 2018-11-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181019_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_application', models.DateField(auto_now_add=True)),
                ('date_reservation_start', models.DateField()),
                ('date_reservation_end', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateField(auto_now_add=True)),
                ('date_reservation_start', models.DateField()),
                ('date_reservation_end', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
            ],
        ),
    ]
