# Generated by Django 2.1.2 on 2018-11-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.IntegerField()),
                ('date_application', models.DateField(auto_now_add=True)),
                ('date_reservation_start', models.DateField()),
                ('date_reservation_end', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='borrower_id',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='facilityreservation',
            name='borrower_id',
        ),
        migrations.RemoveField(
            model_name='facilityreservation',
            name='facility_id',
        ),
        migrations.DeleteModel(
            name='EquipmentReservation',
        ),
        migrations.DeleteModel(
            name='FacilityReservation',
        ),
    ]
