# Generated by Django 2.1.2 on 2018-12-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181116_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation_start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='eventname',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.IntegerField(default=0),
        ),
    ]
