# Generated by Django 2.1.2 on 2018-12-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reservation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2018)),
                ('month', models.IntegerField(default=0)),
                ('start_day', models.IntegerField(default=0)),
                ('end_day', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.TextField(default='N/A')),
                ('date_application', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField(default=2018)),
                ('month', models.IntegerField(default=0)),
                ('start_day', models.IntegerField(default=0)),
                ('end_day', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Borrower')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Facility')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='borrower_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
