# Generated by Django 2.1.2 on 2018-12-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181202_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserve_type',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
