# Generated by Django 2.1.2 on 2018-12-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reservation_reserve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remarks',
            field=models.TextField(default='none'),
        ),
    ]
