# Generated by Django 2.1.2 on 2018-12-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_reservation_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('day', models.IntegerField(default=1)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2018)),
                ('time_start', models.IntegerField(default=6)),
                ('time_end', models.IntegerField(default=21)),
            ],
        ),
    ]
