# Generated by Django 2.1.2 on 2018-12-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181208_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('borrower', models.IntegerField(null=True)),
                ('admin', models.IntegerField(null=True)),
                ('message', models.TextField(default='None')),
            ],
        ),
    ]
